### PR TITLE
Wideband Rev 2

### PR DESCRIPTION
**Pull request by dron0gus**
Screenshot from 2022-04-09 23-04-07
Fixes, improvements, bugfixes, etc

### CODE REVIEW

**Comment by rusefillc** [comment]
@dron0gus please write up changes?

**Comment by dron0gus** [comment]
**Pinout changed**, added silk comments with wire colors for lsu4.9
Second one AC injection resistor for LSU4.2
Reverse voltage protection replaced with diode. Heater+ is protected with fuse and suppressor.
CAN 120R load added.
Vbat sense circuit.
Vm output sense circuit.
Current limiting resistor in virtual ground buffer is now inside feedback loop.
Separate buffer for internal virtual ground users.
Precision amp is changed to GS8332 (dual) - second one is used for Un_sense.
RefDef rearranged and now do not overlaps
PWM heater moved to PB6.

**Comment by rusefillc** [comment]
@dron0gus do we have HW board ID jumpers on this PCB? do we have silkscreen explaining IDs?

**Comment by dron0gus** [comment]
@rusefillc 
Two config jumpers. What silkscreen comment is expected?

**Comment by rusefillc** [comment]
"use XX and XX to set controller index"?

but really the main thing we have it on the board

**Comment by dron0gus** [comment]
There is not so much free space for instruction.
Screenshot from 2022-04-09 23-36-41

**Comment by rusefillc** [comment]
how full is back side of PCB?

**Comment by dron0gus** [comment]
Screenshot from 2022-04-10 00-02-22
noone will look on backside for instructions. )))

**Comment by mck1117** [comment]
image

stray comment that no longer applies

**Comment by mck1117** [comment]
image

R1/3/4/7 can be 1%

**Comment by mck1117** [comment]
image

config straps should have 3.3v option as well, maybe switch to 3 pin jumper footprint instead of resistor?

**Comment by dron0gus** [comment]
> image
> 
> config straps should have 3.3v option as well, maybe switch to 3 pin jumper footprint instead of resistor?

Do we want to detect one of three states on each pin? Otherwise we can enable internal pull-up.

**Comment by dron0gus** [comment]
> image
> 
> R1/3/4/7 can be 1%
> 
> It is not required that this opamp is low offset, so we could use MCP6004 here too.

Yes. But I need one OpAmp. And it was simpler to extend GS8331 to dual, than adding one more mcp600x

**Comment by dron0gus** [comment]
Still thinking on protection of U1D and U1B from shorting Ip and Vm to battery.
Simple solution in unrecoverable protection with burning R5 and R19/R14.

**Comment by mck1117** [comment]
> Do we want to detect one of three states on each pin? Otherwise we can enable internal pull-up.

Yes, we can/do detect all three states: https://github.com/mck1117/wideband/issues/11

**Comment by mck1117** [comment]
> Yes. But I need one OpAmp. And it was simpler to extend GS8331 to dual, than adding one more mcp600x

Ah, fair enough. Makes sense.

Those resistors can still be 1% though, saves a few BOM lines.

**Comment by mck1117** [comment]
1% is probably fine for R22/R45 too. 1% change is only a few degrees C, and the sensor's gain is pretty flat right near the operating point.

**Comment by mck1117** [comment]
image

I would omit the termination resistor. Unlikely that your bus is going to be /just/ a single lambda controller and an ECU. If nothing else, add a default-open jumper footprint.

**Comment by rusefillc** [comment]
@mck1117 says ADV would be one additional resistor?

**Comment by dron0gus** [comment]
@mck1117 do you know what current needs to be injected to Un with R24? Thinking about to move it from 3.3 to 5.0 to make in more stable while Un changes...

**Comment by dron0gus** [comment]
> @mck1117 says ADV would be one additional resistor?

Do we want to support all 3 types in one? Crazy. Ok, will do.

**Comment by dron0gus** [comment]
Added testpoints to unused MCU pins (where possible)
Added LSU_ADV AC injection R
Bias current resistor (LSU4.9) is now controlled by gpio
Added Heater- sense. To check is sensor present/heater problems.
Config pin pull-ups added.
CAN load resistor is NA.

**Comment by dron0gus** [comment]
Gerbers, BOM, drill updated.

**Comment by rusefillc** [comment]
image

image

image


Best fuse holder based on qty available is 

XFCN
MFR.Part #
XF-506P
JLCPCB Part #
C492610

**Pull request merged**
